export const MEMORY_TAGLINES: string[] = [
  "POV: We're the main characters",
  "Slayed every day (no cap)",
  "The chaos we bring",
  "It was a canon event",
  "Certified bestie moment",
  "Unhinged but make it aesthetic",
  "Chronically online, occasionally outside",
  "Delulu but it's working",
  "Soft hours only",
  "This should be illegal (but it's not)",
  "Friends, but make it feral",
  "Vibes were immaculate",
  "Side characters where? Exactly.",
  "Caught in 4K being iconic",
  "Booked, busy, and emotionally unstable",
  "This is why we can't have nice things",
  "We ate and left no crumbs",
  "Main character energy only",
  "Unsupervised and thriving",
  "Besties in our flop era (still cute tho)",
  "Too much lore for one photo",
  "This night had no plot, just vibes",
  "Proof we do in fact go outside",
  "Zero thoughts, just friendship",
  "The group chat could never",
  "Certified core memory",
  "Delusional but adorable",
  "This pic is so us coded",
  "They don't make friendships like this anymore",
];

export const DEFAULT_WRAPPED_TITLES: string[] = [
  "spill the tea on our 2025 friendships ☕",
  "our 2025 friendship era ✨",
  "the year we were unhinged (and loved it) 💅",
  "2025: main character energy only 🎬",
  "proof we're the besties 🫶",
  "our 2025 friendship arc 📖",
  "the year we slayed together 👑",
  "2025: certified bestie moments only 💯",
  "our friendship wrapped (no cap) 🎁",
  "the year we ate and left no crumbs 🍽️",
  "2025: vibes were immaculate ✨",
  "our friendship lore this year 📚",
  "the year we were chronically together 👯",
  "2025: delulu but it's working 🎭",
  "our friendship wrapped (it's giving) 💫",
];
